#!/usr/bin/env php
<?php
/**
 * Japan issues hundreds of PDF files with just a few
 * lines, with no reference to COVID reports.
 * But all files retrieved from the japanese gov site are
 * already from covid related posts.
 * This files adds the checked.txt file to all of them
 * to avoid having to check them one by one.
 */
chdir(__DIR__ .'/../../');
date_default_timezone_set('UTC');

$reports = glob('reports/jp/*', GLOB_ONLYDIR);
foreach ($reports as $path) {
    $discarded = $path.'/discarded.txt';
    if (is_file($discarded)) {
        continue;
    }
    $checked = $path.'/checked.txt';
    if (!is_file($checked)) {
        touch($checked);
    }
}
