#!/usr/bin/env php
<?php
/**
 * Emirates files are manually downloaded
 */
chdir(__DIR__ .'/../../');
date_default_timezone_set('UTC');

$reports = glob('reports/ae/*', GLOB_ONLYDIR);
foreach ($reports as $path) {
    $discarded = $path.'/discarded.txt';
    if (is_file($discarded)) {
        continue;
    }
    $checked = $path.'/checked.txt';
    if (!is_file($checked)) {
        touch($checked);
    }
}
