#!/usr/bin/env php
<?php
chdir(__DIR__ .'/../');
date_default_timezone_set('UTC');

$code = $argv[1] ?? false;
if (empty($code)) {
    exit(1);
}
$path = 'reports/'.$code;
if (!is_dir($path)) {
    exit(1);
}
$reports = glob($path.'/*', GLOB_ONLYDIR);
foreach ($reports as $path) {
    $discarded = $path.'/discarded.txt';
    if (is_file($discarded)) {
        continue;
    }
    $checked = $path.'/checked.txt';
    if (!is_file($checked)) {
        touch($checked);
    }
}
