#!/usr/bin/env php
<?php
/**
 * Goes through reports and deletes the ones that
 * return an error but do not return proper http status code
 */
chdir(__DIR__ .'/..');
date_default_timezone_set('UTC');

$keywords = file(__DIR__.'/../error-keywords.txt');
foreach($keywords as $k=>$v) {
    $v = trim($v);
    if ($v) {
        $keywords[$k] = $v;
    } else {
        unset($keywords[$k]);
    }
}

$errors = 0;
$reports = glob('reports/*/*', GLOB_ONLYDIR);
foreach ($reports as $path) {
    $basename = basename($path);
    if ($basename == 'tmp') {
        continue;
    }
    $discarded = $path.'/discarded.txt';
    $checked = $path.'/checked.txt';
    if (is_file($discarded) || is_file($checked)) {
        continue;
    }
    $path_raw = $path .'/raw.txt';
    if (!is_file($path_raw)) {
        echo "MISSING raw.txt $path\n";
        continue;
    }
    $path_report = $path.'/report.json';
    if (!is_file($path_report)) {
        echo "MISSING report.json $path\n";
        continue;
    }
    $raw = file_get_contents($path_raw);

    foreach ($keywords as $word) {
        if (stripos($raw,$word) !== false) {
            echo "REMOVING $path\n";
            exec("rm -r $path");
            $errors++;
            break;
        }
    }
}

if ($errors) {
    exit(1);
}
