#!/usr/bin/env php
<?php
/**
 * Generates the README.md files of the reports and
 * for each country.
 */
chdir(__DIR__ .'/..');
date_default_timezone_set('UTC');

/**
 * TODO: Add a directory listing hash to avoid running on
 * all directories on each run.
 */

$summary = [];

$sources = glob('reports/*/*.url');
$summary_sources = [];
foreach ($sources as $source) {
    echo "Parsing $source\n";
    $config = parse_ini_file($source);
    $country_code = basename(dirname($source));
    $country = $config['ORG'] ?? $country_code;

    $summary_sources[$country][] = $config;

    if (isset($summary[$country])) {
        continue;
    }

    $source_name = basename($source);

    $files = [];
    $reports = glob(dirname($source).'/*', GLOB_ONLYDIR);
    $updated = 0;
    foreach ($reports as $path) {
        $data = [];
        $discard_file = $path.'/discarded.txt';
        if (is_file($discard_file)) {
            continue;
        }
        $path_file = $path.'/file.pdf';
        $path_report = $path.'/report.json';
        if (is_file($path_report)) {
            $data = json_decode(file_get_contents($path_report), true);
        } else {
            $path_file = current( glob($path.'/*.pdf') );
        }
        if (!is_file($path_file)) {
            file_put_contents($path.'/check', 'MISSING FILES');
            continue;
        }
        $modified = filemtime($path_file);
        $basename = basename($path_file);
        $filesize = filesize($path_file);
        if (empty($data['modified'])) {
            $data['modified'] = $modified;
        }
        if (empty($data['downloaded'])) {
            $data['downloaded'] = $modified;
        }
        if (empty($data['filename'])) {
            $data['filename'] = $basename;
        }
        if (empty($data['output'])) {
            $data['output'] = $basename;
        }
        if (empty($data['size'])) {
            $data['size'] = $filesize;
        }
        if (!is_file($path_report)) {
            file_put_contents($path_report, json_encode($data, JSON_PRETTY_PRINT));
        }
        $path_date = $path .'/date.txt';
        if (is_file($path_date)) {
            $date = trim(file_get_contents($path_date));
            if (is_numeric($date)) {
                $data['modified'] = $date;
            } else {
                $data['modified'] = strtotime($date);
            }
        }
        $data['path'] = $path_file;
        if($data['modified'] > $updated) {
            $updated = $data['modified'];
        }
        $files[] = $data;
    }
    if (!empty($files)) {
        $summary[$country][] = [
            'country' => $country,
            'country_code' => $country_code,
            'config' => $config,
            'files' => $files,
            'updated' => $updated,
        ];
    }
}
ksort($summary);

$summary_file = 'reports/README.md';
file_put_contents($summary_file, "# Reports\n\n");
file_put_contents($summary_file, "| Country | Updated | Files | Sources |\n", FILE_APPEND);
file_put_contents($summary_file, "| --- | --- | --- | --- |\n", FILE_APPEND);
foreach ($summary as $country=>$sources) {
    $updated = 0;
    $files_count = 0;
    $country_code = $sources[0]['country_code'];
    foreach ($sources as $source) {
        if ($source['updated'] > $updated) {
            $updated = $source['updated'];
        }
        $files_count += count($source['files']);
    }
    $sources_count = count($summary_sources[$country]);
    $report_file = 'reports/'.$country_code.'/README.md';
    $report_file_link = str_replace('reports/', '', $report_file);

    $updated_date = gmdate('Y-m-d H:i', $updated).' GMT';
    file_put_contents($summary_file, "| [{$country}]({$report_file_link}) | {$updated_date} | [{$files_count}]({$report_file_link}) | {$sources_count} |\n", FILE_APPEND);

    file_put_contents($report_file, "# {$country}\n\n");
    // Sources
    foreach ($summary_sources[$country] as $src) {
        $url = $src['URL'];
        file_put_contents($report_file, "* [$url]($url)\n", FILE_APPEND);
    }
    file_put_contents($report_file, "\n", FILE_APPEND);

    $files = [];
    foreach ($sources as $source) {
        foreach($source['files'] as $file) {
            $files[] = $file;
        }
    }
    usort($files, function($a,$b) {
        if($a['modified'] == $b['modified']) {
            return 0;
        }
        return ($a['modified'] > $b['modified'] ) ? -1 : 1;
    });

    $lastdate = 'Unknown';
    foreach ($files as $file) {
        $date = gmdate('Y-m-d', $file['modified']);
        if ($date != $lastdate) {
            file_put_contents($report_file, "\n## {$date}\n\n", FILE_APPEND);
            $lastdate = $date;
        }
        $filename = str_replace('_', '\_', $file['filename']);
        if (substr($filename, 0,1) == '"' && substr($filename, -1) == '"') {
            $filename = substr($filename, 1, -1);
        }
        $filename = urldecode($filename);
        $path = str_replace('reports/'.$country_code.'/', '', $file['path']);
        $timestamp = gmdate('H:i', $file['modified']);
        file_put_contents($report_file, "* [{$filename}]({$path}) @{$timestamp} GMT\n", FILE_APPEND);
    }
}


