#!/usr/bin/env php
<?php
/**
 * Goes through files, extracts the text in them
 * and checks if they have any of the keywords.
 * If none of the keywords is found, the file
 * is marked as discarded.
 */
chdir(__DIR__ .'/..');
date_default_timezone_set('UTC');

/**
 * TODO: Add a directory listing hash to avoid running on
 * all directories on each run.
 */

$keywords = file(__DIR__.'/../keywords.txt');
foreach($keywords as $k=>$v) {
    $v = trim($v);
    if ($v) {
        $keywords[$k] = $v;
    } else {
        unset($keywords[$k]);
    }
}

$errors = 0;
$reports = glob('reports/*/*', GLOB_ONLYDIR);
foreach ($reports as $path) {
    $discarded = $path.'/discarded.txt';
    $checked = $path.'/checked.txt';
    if (is_file($discarded) || is_file($checked)) {
        continue;
    }

    $path_file = $path.'/file.pdf';
    $path_report = $path.'/report.json';
    if (!is_file($path_report)) {
        echo "MISSING report.json $path\n";
        $errors++;
        continue;
    }
    $report = json_decode(file_get_contents($path_report), true);
    if (isset($report['output'])) {
        $path_file = $path.'/'.$report['output'];
    }
    $path_raw = $path .'/raw.txt';
    if (!is_file($path_raw)) {
        exec('pdftotext -raw "'.$path_file.'" - > "'.$path_raw.'"');
    }
    $uri = $report['uri'] ?? '';
    $filename = $report['filename'] ?? '';
    $has_keyword = false;

    foreach ($keywords as $word) {
        if (stripos($uri,$word) !== false
            || stripos($filename,$word) !== false) {
            file_put_contents($checked, $word);
            continue 2;
        }
    }

    $raw = file_get_contents($path_raw);
    $raw = preg_replace('/[\s]+/', '', $raw);
    foreach ($keywords as $word) {
        if (stripos($raw,$word) !== false) {
            file_put_contents($checked, $word);
            continue 2;
        }
    }

    if (strlen($raw) < 64) {
        echo "TOO SHORT TO TEST $path\n";
        $errors++;
        continue;
    }

    echo "MISSING KEYWORDS $path\n";
    $errors++;
    continue;
}

if ($errors) {
    exit(1);
}
