#!/usr/bin/env php
<?php
/**
 * Goes through Korea reports and updates their hash
 */
chdir(__DIR__ .'/../../');
date_default_timezone_set('UTC');

$reports = glob('reports/kr/*', GLOB_ONLYDIR);
foreach ($reports as $path) {

    $report = json_decode(file_get_contents($path.'/report.json'),true);
    $path_hash = basename($path);

    if (preg_match('/comfile_fn=(?P<hash>[^\&\"]+)\&/Ui', $report['uri'], $match)) {
        $hash = sha1($match['hash']);
        if ($hash != $path_hash) {
            $new_path = dirname($path).'/'.$hash;
            exec("mv \"$path\" \"$new_path\"");
        }
    }
}

